Boutique.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Boutique.Core.Contracts.Category;
using Boutique.Core.Services.Abstractions.Features;
using Boutique.Web.ViewModel;

namespace Boutique.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetCategoryById(int id)
        {
            var category = await _categoryService.GetCategoryByIdAsync(id);
            if (category == null)
                return NotFound();

            return Ok(category);
        }

        [HttpGet]
        public async Task<IActionResult> CategoryHome()
        {
            var categories = await _categoryService.GetAllCategoriesAsync();
            var viewModel = new CategoryHomeViewModel
            {
                Categories = categories
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddCategory(CreateCategoryDto request)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var category = await _categoryService.AddCategoryAsync(request);

            if (category == null)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Error creating category");
            }

            return RedirectToAction("CategoryHome");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCategory([FromForm] UpdateCategoryDto request)
        {
            if (request == null || !ModelState.IsValid)
            {
                TempData["Error"] = "Invalid data. Please check your inputs.";
                return RedirectToAction("CategoryHome");
            }
            try
            {
                string updateResult = await _categoryService.UpdateCategoryAsync(request.CategoryId, request);

                TempData["message"] = updateResult;

                return RedirectToAction("CategoryHome");
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"Internal server error: {ex.Message}";
                return RedirectToAction("CategoryHome");
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCategory(int id)
        {
            try
            {
                await _categoryService.DeleteCategoryAsync(id);
                TempData["message"] = "Category deleted successfully.";
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"Failed to delete category: {ex.Message}";
            }

            return RedirectToAction("CategoryHome");
        }

    }
}

Boutique.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Boutique.Core.Contracts.Product;
using Boutique.Core.Services.Abstractions.Features;
using Boutique.Core.Services.Exceptions;
using Boutique.Web.ViewModel;
using Boutique.Web.ViewModel.Product;
using Microsoft.AspNetCore.Authorization;

namespace Boutique.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;

        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        [Authorize(Policy = "Admin")]
        [HttpGet]
        public async Task<IActionResult> ProductHome()
        {
            var products = await _productService.GetAllProductsAsync();
            var categories = await _categoryService.GetAllCategoriesAsync();

            var viewModel = new ProductHomeViewModel
            {
                Products = products,
                Categories = categories
            };

            return View(viewModel);
        }
        [Authorize(Policy = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateProduct(CreateProductDto createProductDto)
        {
            try
            {
                var newProduct = await _productService.AddProductAsync(createProductDto);

                TempData["SuccessMessage"] = "Product created successfully!";
                return RedirectToAction("ProductHome");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An unexpected error occurred. Please try again.";
                return RedirectToAction("ProductHome");
            }
        }
        [Authorize(Policy = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var product = await _productService.GetProductByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            var viewModel = new ProductDetailViewModel
            {
                ProductId = product.ProductId,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                Quantity = product.Quantity,
                CategoryName = product.CategoryName,
                Images = product.Images,
                DateCreated = product.DateCreated,
                DateModified = product.DateModified
            };

            return View(viewModel);
        }

        [HttpGet("{productId}")]
        public async Task<IActionResult> GetProductById(int productId)
        {
            try
            {
                var product = await _productService.GetProductByIdAsync(productId);
                return Ok(product);
            }
            catch (Exception ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct([FromForm] UpdateProductDto updateProductDto)
        {
            try
            {
                var updatedProduct = await _productService.UpdateProductAsync(updateProductDto.ProductId, updateProductDto);

                TempData["SuccessMessage"] = "Product updated successfully!";
                return RedirectToAction("ProductHome");
            }
            catch (NotFoundException ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("ProductHome");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An unexpected error occurred. Please try again.";
                return RedirectToAction("ProductHome");
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProduct(int productId)
        {
            try
            {
                await _productService.DeleteProductAsync(productId);
                TempData["SuccessMessage"] = "Product deleted successfully.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Failed to delete this product: {ex.Message}";
            }

            return RedirectToAction("ProductHome");
        }
        public IActionResult ProductDetail()
        {
            return View();
        }
       
    }
}

Boutique.Web/Controllers/ProductVariantController.cs
using Microsoft.AspNetCore.Mvc;
using Boutique.Core.Contracts.ProductVariant;
using Boutique.Core.Services.Abstractions.Features;
using Boutique.Web.ViewModel.ProductVariant;
using Microsoft.AspNetCore.Authorization;

namespace Boutique.Web.Controllers
{
    public class ProductVariantController : Controller
    {
        private readonly IProductVariantService _productVariantService;
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        public ProductVariantController(IProductVariantService productVariantService, IProductService productService, ICategoryService categoryService)
        {
            _productVariantService = productVariantService;
            _productService = productService;
            _categoryService = categoryService;
        }
        [Authorize(Policy = "Admin")]
        [HttpGet]
        public async Task<IActionResult> ProductVariantHome()
        {
            var productVariants = await _productVariantService.GetAllProductVariantsAsync();
            var products = await _productService.GetAllProductsAsync();
            var categories = await _categoryService.GetAllCategoriesAsync();
            var viewModel = new ProductVariantViewModel
            {
                ProductVariants = productVariants,
                Products = products,
                Categories = categories
            };

            return View(viewModel);
        }
        [Authorize(Policy = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateProductVariant(CreateProductVariantDto createDto)
        {
            try
            {
                var result = await _productVariantService.CreateAsync(createDto);

                TempData["SuccessMessage"] = "Product Variant created successfully!";
                return RedirectToAction("ProductVariantHome");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An unexpected error occurred. Please try again.";
                return RedirectToAction("ProductVariantHome");
            }
        }
        [HttpGet("{id}")]
        public async Task<IActionResult> GetProductVariantById(int id)
        {
            var result = await _productVariantService.GetProductVariantByIdAsync(id);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetAllProductVariants()
        {
            var result = await _productVariantService.GetAllProductVariantsAsync();
            return Ok(result);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductVariant([FromForm] UpdateProductVariantDto updateDto)
        {
            try
            {
                var updatedProductVariant = await _productVariantService.UpdateProductVariantAsync(updateDto.ProductVariantId, updateDto);
                TempData["SuccessMessage"] = "Product variant updated successfully.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Failed to update this product variant: {ex.Message}";
            }

            return RedirectToAction("ProductVariantHome");
        }

        [HttpDelete("{productVariantId}")]
        public async Task<IActionResult> DeleteProductVariantById(int productVariantId)
        {
            try
            {
                var isDeleted = await _productVariantService.DeleteProductVariantByIdAsync(productVariantId);
                if (isDeleted)
                {
                    return NoContent();
                }

                return NotFound("Product variant not found");
            }
            catch (KeyNotFoundException ex)
            {
                return NotFound(ex.Message);
            }
        }

    }
}

Boutique.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body id="page-top">
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Boutique Admin</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Store
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("ProductHome", "Product")">
                    <span>Product</span>
                </a>
                <a class="nav-link collapsed" href="@Url.Action("CategoryHome", "Category")">
                    <span>Category</span>
                </a>
                <a class="nav-link collapsed" href="@Url.Action("ProductVariantHome", "ProductVariant")">
                    <span>Product Variant</span>
                </a>
                <a class="nav-link collapsed" href="@Url.Action("AdminTrackOrder", "Admin")">
                    <span>Order</span>
                </a>
                <a class="nav-link collapsed" href="@Url.Action("UserManagement", "Admin")">
                    <span>User</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>  
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>